# Generated by Django 5.2.7 on 2025-10-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='사용자가 입력한 URL', max_length=500, verbose_name='원본 URL')),
                ('final_url', models.URLField(help_text='Redirection 이후 최종 도착 URL', max_length=500, verbose_name='최종 URL')),
                ('domain', models.CharField(help_text='URL의 도메인 부분', max_length=255, verbose_name='도메인')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='페이지 제목')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/', verbose_name='스크린샷')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='분석 시간')),
                ('network_requests', models.IntegerField(default=0, verbose_name='네트워크 요청 수')),
                ('redirects', models.IntegerField(default=0, verbose_name='리다이렉션 수')),
                ('js_errors', models.IntegerField(default=0, verbose_name='JavaScript 오류 수')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('risk_score', models.IntegerField(default=0, help_text='0-100사이 값, 높을 수록 위험', verbose_name='위험도 점수')),
                ('detail_data', models.JSONField(blank=True, help_text='네트워크 트래픽, 포트 스탠 결과 등. .', null=True, verbose_name='상세 분석 데이터')),
            ],
            options={
                'verbose_name': 'URL 분석',
                'verbose_name_plural': 'URL 분석 목록',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
