# Generated by Django 5.2.7 on 2025-10-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlanalysis',
            name='risk_level',
            field=models.CharField(choices=[('low', '낮음'), ('medium', '중간'), ('high', '높음')], default='low', max_length=20, verbose_name='위험 수준'),
        ),
    ]
