# Generated by Django 5.2.7 on 2025-10-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_urlanalysis_risk_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlanalysis',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='urlanalysis',
            name='screenshot_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='스크린샷 경로'),
        ),
    ]
